apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  labels:
    testing.upbound.io/example-name: vpcattach
  name: vpcattach
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    region: us-east-1
