apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: test2
  name: test2
spec:
  forProvider:
    ami: ami-0719cea984ab14a40
    instanceType: t2.micro
    networkInterface:
      - deviceIndex: 0
        networkInterfaceIdRef:
          name: test2
    region: us-east-1
